### ISSUE TITLE
Project not working - NEED to pull submodule XOJO-Unit

### ISSUE THREAD

**Issue by adalseno** [Budjhete/XojoORM#24]
Hi, I tried to start the project but I got a bunch of errors! Looks like some files are missing.
Andrea

**Comment by HeteMacmania** [comment]
can you point me which file or class are missing ?

**Comment by HeteMacmania** [comment]
I just push few fixes in the Develop branch, can you try it ?

**Comment by adalseno** [comment]
Thank you. I tried, but with no luck. When I open the project (latest release of Xojo on Mac) I get the following requests:
- Cannot locate "XojoUnitMenuBar.xojo_menu"
- Locate folder "TestFramework"
- Locate "TestGroup.xojo_code"
- Locate "TestController.xojo_code"
- Locate "Assert.xojo_code"
- Locate "Test_result.xojo_code"
- Locate "TestWindow.xojo_code" (maybe it was xoxo_window")
- Locate "AboutWindow.xojo_window"
- Locate folder Tests
- Locate "XojoUnitTest.xojo_code"
- Locate "TestToolbar.xojo_toolbar"
- Locate "Bug.png"
and I have to guess where to find them.

**Comment by adalseno** [comment]
Hi, merging the code of the dev branch and the master branch I got a working project (it looks like the problems with the dev branch project rely in the unit test): I can search for records, can find them all and fill a listbox, update them (and then refreshing the listbox), but I got stuck with the record creation.
If I create a record as soon as the window starts everything goes fine, but if I try to create a second record I got an error (the id is set to an empty string instead of NULL; test database in SqlLite). What am I doing wrong? I tried to unload the model and, since setting the id textbox to "" didn't work, I tried also to set it to model.pk (after having unloaded the model), but I always get the same error, id is '' instead of NULL.

**Comment by HeteMacmania** [comment]
use only the DEV branch, i did the correction to make it work

**Comment by HeteMacmania** [comment]
oh, and dont use ID in your DB
use PrimaryKey property to chose something else like

TableXYZ :
	noTableXYZ (the primary key)
	Field 1
	Field 2
	etc..

**Comment by adalseno** [comment]
Hi, I'm sorry but the DEV branch still doesn't work. I have the same request as before. Looks like something is missing (an entire folder).

Actually I don't use ID I use the PrimariKey property, but when the ORM builds the create query for the second time the PK (id) value is set to an empty string ('') instead of NULL generating an error.

**Comment by HeteMacmania** [comment]
Hello,

sorry, the unit test wasn't working.  I just made few fix to make it work.

The ORM works pretty well with SQLite and MySQL.

i recommande you to use PK like “noYourTableName” because when you join / groupby / has / sort etc… it’s easier and faster to use only the pk instead of table.pk (because sqlite and mysql doesn’t treat it the same way :-/ and if you want cross compatibility between sqlite and mysql in your app it’s easier... )

PS : sorry for my english, i usually speak french...

**Comment by adalseno** [comment]
Merci, I will try. Have you ever tested it with PostgreSQL?
If you feel more comfortable with French feel free to write in French, I understand it a little bit (I feel more comfortable with English, but if you prefer I can try to write in French).

**Comment by adalseno** [comment]
I'm sorry but I still get the same errors. It looks like a folder is missing from the project (for example the assert function cannot be find, nor the about window etc.).

**Comment by HeteMacmania** [comment]
Did you pull the XojoUnit module too ?

**Comment by adalseno** [comment]
Actually no! Here it is the missing folder. Though I still have some issues ( I tried both the master and the dev branches). Here you are the errors with the master branch:
![schermata 2017-04-03 alle 00 45 21](https://cloud.githubusercontent.com/assets/2405291/24591639/e48e9414-1806-11e7-970e-70e16aba3cef.png)
![schermata 2017-04-03 alle 00 45 09](https://cloud.githubusercontent.com/assets/2405291/24591640/e4bbc588-1806-11e7-8d57-75c58b14448a.png)
![schermata 2017-04-03 alle 00 44 44](https://cloud.githubusercontent.com/assets/2405291/24591641/e4bbe2de-1806-11e7-99ee-abddda0f5b1e.png)

And these are the errors with the dev branch (of XojoUnit):
![schermata 2017-04-03 alle 00 50 03](https://cloud.githubusercontent.com/assets/2405291/24591673/8101774e-1807-11e7-8b18-ef3e79d54235.png)
![schermata 2017-04-03 alle 00 49 50](https://cloud.githubusercontent.com/assets/2405291/24591674/815aa2ec-1807-11e7-8eef-3975be9ec04c.png)

**Comment by HeteMacmania** [comment]
You need to Pull the SubModule XojoUnit
github.com:Budjhete/xojo-unit

**Comment by HeteMacmania** [comment]
Note, in your project, you dont need the XojoUnit
BUT
if you are trying to run the ORM exemple project, you will ABSOLUTELY need XojoUnit, included in the SubModule

NB : Assert is a test from XojoUnit submodule

**Comment by adalseno** [comment]
I opened the XojoUnit project (Desktop) and copied the XojoUnit folder into the project (I also had to delete the database and add the SQLLite database to the project)

**Comment by adalseno** [comment]
I'm not using github. I simply downloaded the zip files.

**Comment by HeteMacmania** [comment]
i know, SQLite broke easily in xojo+github

What do you use to fetch Git projects ?  SourceTree, Tower ?

**Comment by HeteMacmania** [comment]
Feel free to send push request if you want to integrate PostgreSQL

**Comment by adalseno** [comment]
Using git it works, thanks. I will study the code and yes, I'm using postgresql so a version for this db would be great

**Comment by HeteMacmania** [comment]
It will probably work, with some few exception…
